name: Use the action locally to test GH Action functionality

on:
  workflow_dispatch:

jobs:
  execute-action:
    name: Use internal GH Action
    runs-on: ubuntu-latest
    steps:
      - name: Create Medium Post
        uses: philips-software/post-to-medium-action@v0.1
        with:
           integration_token: "${{ secrets.INTEGRATION_TOKEN }}"
           content: "Test content to see if publishing works from GH Action"
           content_format: "markdown"
           notify_followers: "false"
           publication_name: "test-brend-publication"
           tags: "test,tag"
           title: "Test post via GH Actions to Medium"